name: connector
registered_version: Connector-v2

network:
    transformer_num_blocks: 4
    transformer_num_heads: 8
    transformer_key_size: 16
    transformer_mlp_units: [512]
    conv_n_channels: 32

training:
    num_epochs: 1000
    num_learner_steps_per_epoch: 100
    n_steps: 10
    total_batch_size: 256

evaluation:
    eval_total_batch_size: 10000
    greedy_eval_total_batch_size: 10000

a2c:
    normalize_advantage: False
    discount_factor: 1.0
    bootstrapping_factor: 0.95
    l_pg: 1.0
    l_td: 1.0
    l_en: 0.01
    learning_rate: 2e-4
