name: job_shop
registered_version: JobShop-v0

network:
    num_layers_machines: 1
    num_layers_operations: 1
    num_layers_joint_machines_jobs: 2
    transformer_num_heads: 8
    transformer_key_size: 16
    transformer_mlp_units: [512]

training:
    num_epochs: 65
    num_learner_steps_per_epoch: 200
    n_steps: 10
    total_batch_size: 128

evaluation:
    eval_total_batch_size: 500
    greedy_eval_total_batch_size: 500

a2c:
    normalize_advantage: False
    discount_factor: 0.99
    bootstrapping_factor: 0.95
    l_pg: 1.0
    l_td: 1.0
    l_en: 0.01
    learning_rate: 1e-4
