name: pac_man
registered_version: PacMan-v0

network:
    num_channels: [4,4,1]
    policy_layers: [64]
    value_layers: [128]

training:
    num_epochs: 3000
    num_learner_steps_per_epoch: 50
    n_steps: 30
    total_batch_size: 64

evaluation:
    eval_total_batch_size: 100
    greedy_eval_total_batch_size: 100

a2c:
    normalize_advantage: False
    discount_factor: 0.99
    bootstrapping_factor: 0.95
    l_pg: 1.0
    l_td: 1.0
    l_en: 0.01
    learning_rate: 3e-4
