name: rware
registered_version: Rware-v0

training:
    num_epochs: 500
    num_learner_steps_per_epoch: 100
    n_steps: 20
    total_batch_size: 128

evaluation:
    eval_total_batch_size: 5000
    greedy_eval_total_batch_size: 5000
