name: tsp
registered_version: TSP-v1

network:
    transformer_num_blocks: 2
    transformer_num_heads: 8
    transformer_key_size: 16
    transformer_mlp_units: [512]
    mean_cities_in_query: True

training:
    num_epochs: 1000
    num_learner_steps_per_epoch: 100
    n_steps: 100
    total_batch_size: 32

evaluation:
    eval_total_batch_size: 10000
    greedy_eval_total_batch_size: 10000

a2c:
    normalize_advantage: False
    discount_factor: 1.0
    bootstrapping_factor: 0.95
    l_pg: 1.0
    l_td: 1.0
    l_en: 0.005
    learning_rate: 1e-4
