# yaml-language-server: $schema=https://instadeep.aichor.ai/schema/latest/manifest.schema.json
kind: AIchorManifest
apiVersion: 0.2.1

builder:
  image: jumanji
  dockerfile: ./Dockerfile
  context: .
  buildArgs:
    USE_CUDA: "true"

spec:
  operator: jax
  image: jumanji
  command: python jumanji/training/train.py

  tensorboard: # optional, disabled by default
    enabled: false

#  storage: # optional
#    sharedVolume: # optional
#      mountPoint: "/mnt/shared"
#      sizeGB: 10
#    attachExistingPVCs: # optional, array
#      - name: "my-awesome-pvc"
#        mountPoint: "/mnt/my-60tib-dataset"

  types:
    Worker:
      count: 1

      resources:
        cpus: 1
        ramRatio: 30 # RAM per CPU

        accelerators: # optional
          gpu:
            count: 1
            product: Tesla-V100-SXM3-32GB # options: Quadro-RTX-4000, A100-SXM4-80GB, Tesla-V100-SXM3-32GB
            type: gpu

#        machineName: "dgx" # optional
#        shmSizeGB: null # optional
