---
name: Bug report
description: >-
  Report a bug or unexpected behavior to help us improve Jumanji
title: "bug:"
labels:
- bug

body:
- type: markdown
  attributes:
    value: >
      ## Thank you for helping us improve Jumanji!
      * Please first verify that your issue is not already reported using the [Issue search][issue search].
      * If you are asking a question or seeking support, please consider [starting a discussion][Discussions].
      * If you prefer a non-templated issue report, click [here][Raw report].
      [Discussions]: https://github.com/instadeepai/jumanji/discussions
      [issue search]: https://github.com/instadeepai/jumanji/search?q=is%3Aissue&type=issues
      [Raw report]: https://github.com/instadeepai/jumanji/issues/new
- type: textarea
  attributes:
    label: Description
    description: >-
      A concise description of the bug, preferably including self-contained
      code to reproduce the issue.
    placeholder: |
      Text may use markdown formatting.
      ```python
      # for codeblocks, use triple backticks
      ```
  validations:
    required: true
- type: input
  attributes:
    label: What Jumanji version are you using?
    placeholder: For example jumanji v0.1.0
- type: input
  attributes:
    label: Which accelerator(s) are you using?
    placeholder: CPU/GPU/TPU
- type: input
  attributes:
    label: Additional System Info
    placeholder: Python version, OS (Linux/Mac/Windows/WSL), etc.
- type: textarea
  attributes:
    label: Additional Context
    description: >-
      Add any other context about the problem here?
  validations:
    required: false
- type: textarea
  attributes:
    label: (Optional) Suggestion
    description: >-
      Reason for the bug and/or suggestion to fix it
  validations:
    required: false
