defaults:
    - _self_
    - env: connector  # [bin_pack, cleaner, connector, cvrp, game_2048, job_shop, knapsack, maze, minesweeper, rubiks_cube, snake, tsp]

agent: a2c  # [random, a2c]

seed: 0

logger:
    type: neptune  # [neptune, tensorboard, terminal]
    save_checkpoint: false  # [false, true]
    name: ${agent}_${env.name}
