name: bin_pack
registered_version: BinPackValueBased-v0

env_settings:
    reward_fn: ValueBasedDenseReward
    generator: RandomValueProblemGenerator

generator_settings:
    max_num_items: 20
    max_num_ems: 40
    split_num_same_items: 2


network:
    num_transformer_layers: 2
    transformer_num_heads: 8
    transformer_key_size: 16
    transformer_mlp_units: [512]

training:
    num_epochs: 5
    num_learner_steps_per_epoch: 5
    n_steps: 30
    total_batch_size: 2

evaluation:
    eval_total_batch_size: 2
    greedy_eval_total_batch_size: 2

a2c:
    normalize_advantage: False
    discount_factor: 1.0
    bootstrapping_factor: 0.95
    l_pg: 1.0
    l_td: 1.0
    l_en: 0.005
    learning_rate: 1e-4
